engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      keyword-spacing:
        enabled: false
ratings:
  paths:
  - www/pages
  - www/templates
  - www/css
  - www/directives
  - "**.js"
exclude_paths:
- www/bower_components/*
- hooks/*
- platforms/*
- node_modules/*
- plugins/*
- resources/*
- www/lib/*
